return {
	-- Necro991, I don't know which mod it is
	neo_MS_scout                  = { 3, 2, 0 },
	neo_MS_1                      = { 3, 2, 0 },
	neo_MS_2                      = { 3, 2, 0 },
	neo_MS_3                      = { 3, 2, 0 },
	neo_MS_4                      = { 3, 2, 0 },
	neo_MS_5                      = { 3, 2, 0 },
	zeon_MS_scout                 = { 3, 2, 0 },
	zeon_MS_1                     = { 3, 2, 0 },
	zeon_MS_2                     = { 3, 2, 0 },
	zeon_MS_3                     = { 3, 2, 0 },
	zeon_MS_4                     = { 3, 2, 0 },
	zeon_MS_5                     = { 3, 2, 0 },
	zeon_MS_P                     = { 3, 2, 0 },
	axis_MS_scout                 = { 3, 2, 0 },
	axis_MS_1                     = { 3, 2, 0 },
	axis_MS_2                     = { 3, 2, 0 },
	axis_MS_3                     = { 3, 2, 0 },
	axis_MS_4                     = { 3, 2, 0 },
	axis_MS_5                     = { 3, 2, 0 },
	ball                          = { 3, 2, 0 },
	gm                            = { 3, 2, 0 },
	white_base                    = { 0, 0, 10 },
}
